### ISSUE TITLE
PlayerUse isn't handling doors.

### ISSUE THREAD

**Issue by crazycarpet** [crazycarpet/GTA-Evocity-Stories-Issues#6]
:/

**Comment by Codeblockz** [comment]
Unfixable w/ Garry's Mod as is because the way Source Engine works players can click use beside the door and still access them. Issue closed.

**Comment by crazycarpet** [comment]
Unfixable w/ Garry's Mod as is because the way Source Engine works players can click use beside the door and still access them. Issue closed.
